version: '3.4'

services:
  contactmanagement.ui:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      mariadbConnection: Server=host.docker.internal,3306;Database=ContactManagement;Uid=root;Pwd=root;
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
          # copy the sql script to create tables
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    environment:    
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ContactManagement

  #mariadbUI:
  #  image: adminer
  #  ports:
  #    - 8080:8080

volumes:
  mariadb: