CREATE TABLE IF NOT EXISTS ContactUser (
    `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Contact` VARCHAR(100) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL
);